---
title: "Human scheduling of perceptual tasks"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: true
editor_options:
  chunk_output_type: console
---

(REP Title: Prioritizing Dot Discrimination Tasks)

Daniel R. Little^1^, Ami Eidels^2^, and Deborah J. Lin^1^


^1^ The University of Melbourne, ^2^ The University of Newcastle

# Scheduling Project

Preregistration of our hypotheses and data analysis plan are available here: [Preregistration Document](prereg.html) and [OSF](https://osf.io/3kfh6/)


# Overview

Scheduling theory is concerned with the development of policies which determine the “optimal allocation of resources, over time, to a set of tasks” (Parker, 1995). Scheduling problems have been studied extensively in the context of operations research and computer science, where optimal policies have been established for many cases. However, almost no research has examined how cognitive and perceptual mechanisms perform with respect to these optimal policies. 

For many types of goals, such as minimizing the number of tasks completed after a deadline or completing as many tasks as possible in a given length of time, an optimal schedule can be determined (Chretienne et al., 1995). In the present study, we are focused on the scheduling of tasks that vary in difficulty where the goal is to complete as many tasks as possible prior to the deadline. In this case, it is optimal to complete subtasks in order of shortest to longest completion time.

We conducted a number of experiments in which we controlled the difficulty of each subtask by requiring perceptual decisions with known properties. For example, in Experiments 1-3, each subtask is a Random Dot Kinematogram (RDK). In an RDK, dots are moving across an aperture on the screen in a pseudo-random fashion. The participant must to determine whether more dots are moving coherently to the right or to the left. Multiple RDK patches will be presented on the selection screen. Participants will click on the RDK they want to complete, indicate the direction of motion in that patch, and then return to the main screen to select the next RDK. The RDK's will vary in coherence and consequently, difficulty and average completion time (Ludwig & Evens, 2017).

Four experiments were completed online: 

# [Experiment 1](exp1_nodelay.html): *Four RDK Subtasks with No Delay* 

In this experiment, there were two conditions, one using fixed locations of task difficulty on each trial and one using random locations of task difficulty on each trial. In each condition, subjects completed several trials selecting and completing RDK tasks when there was no deadline for completing all of the subtasks and where there was a six second deadline for completing all of the subtasks. There were four subtasks. When an error was made on the RDK task, the direction of the RDK was immediately restarted with a potentially new sampled direction. 

# [Experiment 2](exp2_errordelay.html): *Four RDK Subtasks with Error Delay* 

This experiment was identical to Experiment 1, with one exception. When an error was made on the RDK direction judgment, a 500 msec delay was inserted before resampling the RDK direction and restarting the RDK motion. Both fixed and random location conditions were used. 

# Experiment 3: *Eight RDK Subtasks with Error Delay* 

In this experiemnt, we increased the number of RDK subtasks to eight. In the timed condition, a 12 second deadline was applied.  Only the fixed location condition was tested.

# [Experiment 4](exp4_pixeldelay.Rmd): *Four Pixel Brightness Subtasks with Error Delay* 

In this experiment, we substituted an pixel brightness judgment for each RDK subtask. In the pixel brightness subtask, participants had to judge whether the number of black pixels in a 100 x 100 patch were greater or less than 50%. We again only tested the fixed location condition with a 500 msec delay after an error before the patch was resampled. 

In all experiments, each subtask varied in diffculty, either by manipulating the coherence of the RDK or by manipulating the number of black pixels in Experiment 4. Patches varied from Very Easy to Very Hard. Text labels were presented on each patch so that the difficulty could be discerned without viewing the subtask. 


